### ISSUE TITLE
Add link to http://www.scalatest.org/plus/play in description

### ISSUE THREAD

**Issue by aaabramov** [playframework/scalatestplus-play#113]
It can be done in repository settings.
Edit =>
<img width="1005" alt="screen shot 2018-05-23 at 12 39 38" src="https://user-images.githubusercontent.com/11317222/40416824-f7d297d8-5e86-11e8-8926-3adc1c4a5b37.png">
Website =>
<img width="992" alt="screen shot 2018-05-23 at 12 41 49" src="https://user-images.githubusercontent.com/11317222/40416829-fbeb558a-5e86-11e8-9b5d-2f6b9943858d.png">
Save.

**Comment by marcospereira** [comment]
Nice reminder. Thank you, @aaabramov.

I think linking to scalatest.org/plus/play was not the best option because it is pretty outdated there (still linking to Play 2.2 docs). Instead, I've added a link to the latest docs of how to use ScalaTest + Play.
