### ISSUE TITLE
4.0.1 JAR on Maven Central has malformed META-INF/MANIFEST.M

### ISSUE THREAD

**Issue by kojustin** [playframework/scalatestplus-play#138]
I was having trouble using the edit 4.0.1 JAR.

I downloaded it and cracked it open.

```
curl -O -L http://central.maven.org/maven2/org/scalatestplus/play/scalatestplus-play_2.12/4.0.1/scalatestplus-play_2.12-4.0.1.jar
tar -xf scalatestplus-play_2.12-4.0.1.jar
cat META-INF/MANIFEST.MF
```

Looks like an extra newline got inserted into the `Implementation-URL` field.
```
Manifest-Version: 1.0
Implementation-Title: scalatestplus-play
Implementation-Version: 4.0.1
Specification-Vendor: org.scalatestplus.play
Specification-Title: scalatestplus-play
Implementation-Vendor-Id: org.scalatestplus.play
Specification-Version: 4.0.1
Implementation-URL: https://github.com/playframework/scalatestplus-pla
 y
Implementation-Vendor: org.scalatestplus.play
```

**Comment by kojustin** [comment]
Looks like 4.0.0 has the same. I thought my issue was related, but it's not.

**Comment by renatocaval** [comment]
@kojustin is this still a valid issue? can it be closed?

**Comment by kojustin** [comment]
@renatocaval it's still real, there is still an extra newline in there. It just wasn't the cause of my troubles. I don't know if it's actually causing anything to break and it's been in there since at least 4.0.0.

**Comment by marcospereira** [comment]
> I was having trouble using the edit 4.0.1 JAR.

Could you explain what problem is this generating? Asking because it is not invalid, but in fact, generated following the [manifest specification](https://docs.oracle.com/javase/8/docs/technotes/guides/jar/jar.html#Manifest_Specification):

> Line length:
>
>    No line may be longer than 72 bytes (not characters), in its UTF8-encoded form. If a value would make the initial line longer than this, it should be continued on extra lines (each starting with a single SPACE).

If you are manually parsing the manifest file, you need to consider this.

**Comment by kojustin** [comment]
The problem was user error. 

I was digging around trying to figure out what was wrong thought the newline looked weird. Looks like I was wrong and that's how it's supposed to look.

**Comment by kojustin** [comment]
Closing.
