### ISSUE TITLE
[build] Travis uses sauce Labs limited to 5 concurrent jobs

### ISSUE THREAD

**Issue by ignasi35** [playframework/scalatestplus-play#148]
When migrating to travis-ci.com we increased the number of workers to _up-to_ `13`. This surfaced an issue in the build:

 - Sauce Labs limits to `5` the number of concurrent jobs so it's not uncommon to see job failures when all the Travis worker pool is available.

This is currently fixed using https://blog.travis-ci.com/2014-07-18-per-repository-concurrency-setting but that's not git tracked or explicit in `.travis.yml`.

**Comment by ignasi35** [comment]
An option is to merge scripts into one fat script doing `test`,  `validateCode`, etc...

Another option is to split the build into stages of 4 jobs each (each stage is a JDK+SCALA_VERSION combination).

**Comment by ignasi35** [comment]
I don't think we need the Sauce Labs add-on on every job (I don't think it's used in `validateCode`, for example) so maybe setting the add-on conditionally could be useful too.

**Comment by mkurz** [comment]
How was that sauce labs actually used? For browser testing I guess, bit I don't think we need it anymore...
