### ISSUE TITLE
deprecated WebBrowser is used

### ISSUE THREAD

**Issue by alexandervanhecke** [playframework/scalatestplus-play#170]
`OneBrowserPerSuite` (and other classes) use the deprecated `selenium.WebBrowser` class instead of the new `org.scalatestplus.selenium.WebBrowser`.  Since I'm using the `-Xfatal-warnings` flag, I'm forced to upgrade my tests using `selenium.WebBrowser` to `org.scalatestplus.selenium.WebBrowser`.  But tests also inheriting from `OneBrowserPerSuite` now have conflicting definitions of `WebBrowser`, which introduces another compliation error.  

will provide a pull request.

**Comment by alexandervanhecke** [comment]
Thank you for signing the Lightbend CLA.

If you have already sent a pull request please add a comment to the pull request saying you did sign the CLA.

We are looking forward to your contributions!

**Comment by marcospereira** [comment]
Thank you, @alexandervanhecke. A pull request would be very helpful.

**Comment by alexandervanhecke** [comment]
see https://github.com/playframework/scalatestplus-play/pull/171
