### ISSUE TITLE
MiMa validation for the `2.13` artifact

### ISSUE THREAD

**Issue by ignasi35** [playframework/scalatestplus-play#211]
CI fails the mima validation for the `2.13` jobs because the task can't find the artifacts for `2.13` in the version `4.0.0` (because [`2.13` was only added in `4.0.3`](http://repo1.maven.org/maven2/org/scalatestplus/play/scalatestplus-play_2.13/))

_Originally posted by @ignasi35 in https://github.com/playframework/scalatestplus-play/pull/209#issuecomment-558073183_

**Comment by dwijnand** [comment]
Passing with https://github.com/playframework/scalatestplus-play/pull/213:

```
[info] scalatestplus-play-root: mimaPreviousArtifacts is empty, not analyzing binary compatibility.
[info] scalatestplus-play: mimaPreviousArtifacts is empty, not analyzing binary compatibility.
```
