### ISSUE TITLE
ScalaTest 3.1.0 Support

### ISSUE THREAD

**Issue by margussipria** [playframework/scalatestplus-play#214]
There is new version for ScalaTest and it would be nice to have official support for that.

This should be tested with new ScalaTest before 5.0.x is released for Play Framework 2.8.x, upgraded ScalaTest with 5.1.x release after new PlayFramework is released.

**Comment by marcospereira** [comment]
This requires https://github.com/scalatest/scalatestplus-selenium/pull/7 and https://github.com/scalatest/scalatestplus-scalacheck/issues/17. If they make in time, then yes, we will have a release compatible with 3.1.0. If not, we can always release a scalatestplus-play version that is compatible with Play 2.8.x and scalatest 3.1.0.

**Comment by nafg** [comment]
Hi what's the status of this

**Comment by raboof** [comment]
https://github.com/scalatest/scalatestplus-scalacheck/issues/17 is out.

While https://github.com/scalatest/scalatestplus-selenium/pull/7 is not merged yet, scalatestplus-selenium is released for 3.1.1, so perhaps that's sufficient.

Perhaps you could try preparing a PR?

**Comment by raboof** [comment]
This has been done in #220

**Comment by nafg** [comment]
Looks like it's #252 that it was merged in

**Comment by nafg** [comment]
It seems from github releases that it was released in 5.1.0, but the README hasn't been updated

**Comment by raboof** [comment]
> It seems from github releases that it was released in 5.1.0, but the README hasn't been updated

Good point, added to #258
