### ISSUE TITLE
Versions page and Github releases don't mention 1.4.0-M4

### ISSUE THREAD

**Issue by manuelkiessling** [playframework/scalatestplus-play#25]
I just realized that a version `1.4.0-M4` exists, but neither http://www.scalatest.org/plus/play/versions nor https://github.com/scalatest/scalatestplus-play/releases mention it. Is that on purpose? Are there any reasons to not use M4 for new Play 2.4.x projects?

**Comment by bvenners** [comment]
Sorry, didn't realize it still said M3. Yes, 1.4.0-M4 is the latest. I'll update the site this week.

**Comment by marcospereira** [comment]
1.4.0 version is now listed in http://www.scalatest.org/plus/play/versions and project README.
