### ISSUE TITLE
Release for ScalaTest 3.1.x

### ISSUE THREAD

**Issue by kiranbayram** [playframework/scalatestplus-play#272]
Hello there,

could you please release a version which supports ScalaTest `3.1.x`? Thanks a lot in advance.

Cheers :)

**Comment by raboof** [comment]
the latest version, 5.1.0, supports 3.1.x, right?

**Comment by kiranbayram** [comment]
ah really, i didn't see that in github releases

**Comment by kiranbayram** [comment]
5.1.x supports scalatest 3.1.x
