### ISSUE TITLE
ScalaTest 3.0 Support

### ISSUE THREAD

**Issue by schmitch** [playframework/scalatestplus-play#28]
Currently I think it would be great if we would get ScalaTest 3.0 support.
I also don't think that Play-2.5 will be released before ScalaTest 3.0 is released.

**Comment by jeffmay** [comment]
I just created a project to enable better interop between Play's `ResultExtractors` and ScalaTest's `AsyncTestSuite`: https://github.com/jeffmay/play-test-ops

I still need to add some things like coverage and readme and such, but the code will likely not change. I've been using it for testing a couple projects now, but I pulled it out into a separate project to share.

**Comment by lnism** [comment]
Meanwhile scalatest 3.0 is released

**Comment by lnism** [comment]
Would be great to have a release now that scalatest 3.0 support is in

**Comment by schmitch** [comment]
closed via https://github.com/playframework/scalatestplus-play/pull/58
