### ISSUE TITLE
MockitoSugar is not longer part of ScalaTest

### ISSUE THREAD

**Issue by toshetah** [playframework/scalatestplus-play#294]
Examples still contains references to `MockitoSugar`, as it can be seen [here](https://github.com/playframework/scalatestplus-play/search?q=MockitoSugar).

`MockitoSugar` is no longer part of Scalatest, in version 3.1.1 (which is curretly [used](https://github.com/playframework/scalatestplus-play/blob/5.1.0/build.sbt#L30)),  as used in this project, as you can see [here](https://github.com/scalatest/scalatest/search?q=MockitoSugar). 

Therefore there are broken links in the docs, for example [here](https://github.com/playframework/scalatestplus-play/blob/fbe3fcf4d0019f1389e682c1c248ea7a8c876fe5/docs/manual/working/scalaGuide/main/tests/ScalaTestingWithScalaTest.md#mockito)(click on MockitoSugar in this section), and examples that cannot compile, such as [here](https://github.com/playframework/scalatestplus-play/blob/e420c027d44c93a7b2fc29cbc64eeede3f91f7c7/docs/manual/working/scalaGuide/main/tests/code/UserServiceSpec.scala) and [here](https://github.com/playframework/scalatestplus-play/blob/e420c027d44c93a7b2fc29cbc64eeede3f91f7c7/docs/manual/working/scalaGuide/main/tests/code/ExampleMockitoSpec.scala).

**Comment by raboof** [comment]
Right, it moved from scalatest itself to scalatestplus-mockito, https://github.com/scalatest/scalatestplus-mockito

The examples definitely build: they are compiled as part of our CI (see https://travis-ci.com/github/playframework/scalatestplus-play/jobs/446711309#L3245 for an example of a manually-introduced failure)

In any case, the documentation definitely needs updating to point to the right places.

Would you be interested in contributing?

**Comment by toshetah** [comment]
Sure! I hope I'll get to it in the next couple of days. Do you have any specific guidelines for this fix, accept for what exists in the contributing part in the readme?

**Comment by raboof** [comment]
Great! I don't think I have any particular extra guidelines.

**Comment by toshetah** [comment]
I can't compile the project in intellij. This is the error I am getting:

/Library/Java/JavaVirtualMachines/jdk1.8.0_212.jdk/Contents/Home/bin/java -Djline.terminal=jline.UnsupportedTerminal -Dsbt.log.noformat=true -Dfile.encoding=UTF-8 -Didea.managed=true -Dfile.encoding=UTF-8 -jar /Users/tshetah/Library/Application Support/JetBrains/IntelliJIdea2020.2/plugins/Scala/launcher/sbt-launch.jar
[info] welcome to sbt 1.3.13 (Oracle Corporation Java 1.8.0_212)
[info] loading global plugins from /Users/tshetah/.sbt/1.0/plugins/project/project
[info] loading global plugins from /Users/tshetah/.sbt/1.0/plugins/project
[info] loading settings for project global-plugins from plugins.sbt ...
[info] loading global plugins from /Users/tshetah/.sbt/1.0/plugins
[info] loading settings for project scalatestplus-play-build from plugins.sbt ...
[info] loading project definition from /Users/tshetah/work/workspace/games/scalatestplus-play/project
[info] loading settings for project scalatestplus-play-root from build.sbt ...
[info] set current project to scalatestplus-play-root (in build file:/Users/tshetah/work/workspace/games/scalatestplus-play/)
[error] Failed to derive version from git tags. Maybe run git fetch --unshallow? Version: HEAD+20201126-0124

I am using java 8. @raboof , do you know what can it be?

**Comment by raboof** [comment]
> [error] Failed to derive version from git tags. Maybe run git fetch --unshallow? Version: HEAD+20201126-0124

Have you tried running `git fetch --unshallow`?

**Comment by toshetah** [comment]
Yes. I get:
```
TomerShetahMac:scalatestplus-play tshetah$ git fetch --unshallow
fatal: --unshallow on a complete repository does not make sense
```

**Comment by raboof** [comment]
Hmm, that's weird. Apparently `dynverGitDescribeOutput.value.hasNoTags` returns 'true' for you, which is weird when you have the whole repo.

You could try `git fetch origin --tags`, if that still doesn't work then just comment out lines 42-49 from `build.sbt` (but remember not to commit that)

**Comment by raboof** [comment]
Updated in #296
