### ISSUE TITLE
Aborted tests not reported in JUnit XML reporter - support scalatest 3.2.x

### ISSUE THREAD

**Issue by Dogacel** [playframework/scalatestplus-play#430]
https://github.com/scalatest/scalatest/issues/2100

Seems like this bug is resolved in 3.2.x, can we get a version of the scalatestplus-play that supports scalatest 3.2.x? Maybe we can also override version manually? What do you think?

**Comment by ihostage** [comment]
Hi, @Dogacel!
> Seems like this bug is resolved in 3.2.x, can we get a version of the scalatestplus-play that supports scalatest 3.2.x?

Yes, of course. Would you be keen to provide a pull request for that feature? 

> Maybe we can also override version manually? What do you think?

I think it won't give us a profit, because ScalaTest `3.2.x` isn't binary compatible with `3.1.x` 🤷‍♂️  (https://www.scalatest.org/release_notes/3.2.0)

**Comment by Dogacel** [comment]
@ihostage can take a look when I have time 😆 

It seems like 6.x already uses scala test 3.2, but it is incompatible with scala ver `2.12`. Would it still make sense to support 2.12? We can consider upgrading to 2.13 internally (and we should some time).

**Comment by ihostage** [comment]
> Would it still make sense to support 2.12?

No, Play `2.9.x` won't support Scala `2.12` (https://github.com/playframework/playframework/pull/10956). I think ScalaTest+Play `6.x` should be compatible only with Play `2.9.+` and ScalaTest `3.2.+`

Moreover, looks like it's already done in https://github.com/playframework/scalatestplus-play/pull/353 and final ScalaTest+Play `6.0.0` will be released right after Play `2.9.0`. Currently, you can try to use a milestone version of `6.x` 😉

**Comment by mkurz** [comment]
Releases with scalatest 3.2.x are out.
