### ISSUE TITLE
Update Scalatest references

### ISSUE THREAD

**Issue by wsargent** [playframework/scalatestplus-play#44]
Also filed as https://github.com/playframework/playframework/issues/5759

The documentation for Scalatest / Play uses outdated version numbers.

https://www.playframework.com/documentation/2.5.x/ScalaTestingWithScalaTest#Using-ScalaTest-+-Play

https://github.com/playframework/scalatestplus-play/blob/master/docs/manual/working/scalaGuide/main/tests/ScalaTestingWithScalaTest.md

Also, I think the URL is wrong -- rather than point to http://www.scalatest.org/plus/play/versions it should point to https://github.com/playframework/scalatestplus-play

**Comment by estsauver** [comment]
I believe the first half of this has been updated in this commit: https://github.com/playframework/scalatestplus-play/commit/7696d3d006218623e4074d2255ee4f393d14cf91

For the second commit, I believe there is existing work being tracked in https://github.com/playframework/scalatestplus-play/issues/54 to update the versions versions versions page. That could conceivably just be replaced with the link to the project, but I think we should probably move the scalatest <-> play version table there for folks still working with older versions. 

People working on older versions already don't get dependency injection for free, we shouldn't also punish them with a scalatest version hunt. :)
