### ISSUE TITLE
Update readme to explain Play version compatibility

### ISSUE THREAD

**Issue by gmethvin** [playframework/scalatestplus-play#45]
I noticed a lot of people on the play mailing list are confused when they upgrade their app and their tests suddenly break. It would be helpful if the readme clearly explained which version they are supposed to be using for each version of Play.

**Comment by bvenners** [comment]
I agree. Was planning on doing that. The matrix is here:

http://www.scalatest.org/plus/play/versions

But it should be moved to the readme on this repo so every committer can easily edit it.

**Comment by marcospereira** [comment]
There is now a version matrix at README file.
