### ISSUE TITLE
Add test suites and options for compile time dependency injection

### ISSUE THREAD

**Issue by wsargent** [playframework/scalatestplus-play#49]
ScalaTest Plus uses GuiceApplicationBuilder as the default Application if none is defined, as the default argument.

Ideally this functionality should be broken out so that users who are leveraging a compile time DI framework as an application builder can leverage classes without having to reimplement code.

There's a sample project here that shows equivalent compile time DI tests using manual compile time DI.  It's not hard, but you have to know the source code and where the app is being created before you can get started writing tests.

https://github.com/playframework/play-scala-compile-di-with-tests

**Comment by markglh** [comment]
I'll pick this up as we've implemented something similar in our project, pr coming soon....

**Comment by gmethvin** [comment]
Fixed by #85
