### ISSUE TITLE
Update the Versions, Versions, Versions page

### ISSUE THREAD

**Issue by jducoeur** [playframework/scalatestplus-play#54]
Currently, the [Versions, Versions, Versions page](http://www.scalatest.org/plus/play/versions) lists the correct version of scalatestplus-play to use -- but the links to the ScalaDocs are messed up.  Specifically, _all_ of the versions point to the 1.0.0 docs!  I just lost a fair while trying to figure out why my tests weren't working after upgrading to Play 2.4; eventually I realized it was because I was looking an antique and out-of-date Scaladoc, which didn't match the version 1.4.0 that I was actually using.

I'm now working around this by reading the Scaladoc comments directly in the source code, but it would help the community if these links got fixed...

**Comment by marcospereira** [comment]
Closing this.

The page is actually part of [scalatest-website](https://github.com/scalatest/scalatest-website/) repository, as you can see [here](https://github.com/scalatest/scalatest-website/blob/master/app/views/plus/playVersions.scala.html). Also, there is already a PR to add the most recent major version: scalatest/scalatest-website#55.
