### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by aeons** [playframework/scalatestplus-play#62]
Any ETA on when a new version with the ScalaTest 3 changes will be released?

**Comment by mikla** [comment]
+1

**Comment by gmethvin** [comment]
It probably makes sense to separate the ScalaTest 2 and 3 versions (and keep maintaining them both) since we don't want to force users on Play 2.5.x to upgrade mid-release. Maybe version 2.x should support ScalaTest 3?

**Comment by marcospereira** [comment]
Current master is not stable enough to be released. Our build is broken and we depend on some small scalatest fixes. See https://github.com/playframework/scalatestplus-play/pull/61 and https://github.com/scalatest/scalatest/pull/962.

**Comment by makubi** [comment]
The currently released scalatestplus-play version depends on play-ws 2.5.0 which depends on async-http-client 2.0.0-RC9 which packages adapted Netty classes (under the same package / class name but a different groupid / artifactid).

This results in multiple versions of some Netty classes on the classpath which in fact makes scalatestplus-play with the playframework unusable, if you do not explicitly exclude the problematic dependency org.asynchttpclient:netty-resolver-dns:2.0.0-RC9 and include its transitive dependencies.

The classes seem to be removed in the current async-http-client used by the latest play-ws dependency.

**Comment by wsargent** [comment]
Can you test out the milestone build:

https://groups.google.com/d/msg/play-framework/KLpcJGzqbbI/k9DENVgDBAAJ

"org.scalatestplus.play" %% "scalatestplus-play" % "2.0.0-M1" % Test

**Comment by marcospereira** [comment]
After merging #69 we can do a RC or even a final version.

@wsargent, WDYT?
