### ISSUE TITLE
Will there be `GuiceOneAppPerAsyncSuite`?

### ISSUE THREAD

**Issue by scweang** [playframework/scalatestplus-play#70]
I just downloaded the 2.0.0-M1 and found that there is no async mode of `GuiceOneAppPerSuite`. Just wondering if there would be one.

**Comment by wsargent** [comment]
There is not currently.  Part of the problem is that Play has global state, which means that if we ran several applications against each other, you wouldn't know what `Play.current` referred to.  We can't get around this until Play 3.0.
