### ISSUE TITLE
Publish with Scala 2.12?

### ISSUE THREAD

**Issue by deontologic** [playframework/scalatestplus-play#71]

**Comment by marcospereira** [comment]
The current version of scalatestplus-play depends on [Play 2.5.10](https://github.com/playframework/scalatestplus-play/blob/master/build.sbt#L19) and I think we don't have (yet) a Play 2.5.x release targeting Scala 2.12.

**Comment by mslinn** [comment]
The docs currently say that Play 2.6.x / Scala 2.12.x is supported, and that the dependency is:

    "org.scalatestplus.play" %% "scalatestplus-play" % "2.0.0-M1" % "test"

However that is not found. I did get this dependency to work, however:

    "org.scalatestplus.play" %% "scalatestplus-play" % "2.0.0-M2" % "test"

The docs need to be updated from referencing 2.0.0-M1 to now reference 2.0.0-M2.

**Comment by marcospereira** [comment]
@mslinn see #76.

**Comment by mslinn** [comment]
:)

**Comment by marcospereira** [comment]
Closing this since we released 2.0.0-M2 with Scala 2.12 support.
