### ISSUE TITLE
Routes not loading

### ISSUE THREAD

**Issue by onelson** [playframework/scalatestplus-play#99]
Based on the examples in the docs, and the tests provided with the scala play starter project, I wrote a couple tests for a new app. Unexpectedly, the requests I make in my tests come back as 404s. I'm wondering if there's some special step I need to take to ensure the routes are compiled for tests?

Here are the tests... maybe I'm missing something obvious:

```scala
import org.scalatestplus.play._
import org.scalatestplus.play.guice.GuiceOneAppPerSuite
import play.api.test._
import play.api.test.Helpers._
import play.api.libs.json.Json


class Routes extends PlaySpec with GuiceOneAppPerSuite {

  "Shotgun Routes" should {
    "find_one should be able to find onelson" in  {
      val req = FakeRequest(POST, "/sg/relay/find_one")
        .withJsonBody(Json.parse("""{"kwargs":{"entity_type":"HumanUser","filters":[["login","is","onelson"]]}}"""))
      val resp = route(app, req).get
      status(resp) mustBe OK
      contentType(resp) mustBe Some("application/json")
      (contentAsJson(resp) \ "id").as[Int] mustBe 948
    }
  }

  "DSE Routes" should {
    "sla vert labels should be able OK" in  {
      val req = FakeRequest(GET, "/dse/sla/vert-labels")
      val resp = route(app, req).get
      status(resp) mustBe OK
      contentType(resp) mustBe Some("application/json")
      contentAsString(resp) must include ("Asset")
    }
  }

}
```

The requests, as written, should match what I have in my routes file, and the app is working when I push requests to it in practice.

```
POST    /sg/relay/:methodName    controllers.RelayController.run(methodName: String)
GET     /dse/:graph/vert-labels      controllers.AtlasLegacyController.vertLabels(graph: String)
POST    /dse/:graph/gremlin          controllers.AtlasLegacyController.gremlin(graph: String)
```

Is there something missing?

I'm running Play 2.5.15, with scalatestplus-play 2.0.0.

Thanks,
Owen

**Comment by onelson** [comment]
Chatting about this on twitter, I started to wonder if there aren't extra steps required for testing routes for controllers that use DI to inject this or that. My routes depend on services provided by DI, so maybe that's where the break is. Seems really non-obvious based on the docs, however.

**Comment by marcospereira** [comment]
Hi @onelson, this should work or at least I can't see any obvious problem. Do you have the time to create a small project to reproduce this problem?

Best.

**Comment by onelson** [comment]
I was preparing the repro project, but in the process, I think I learned a critical piece of info.

Running tests through IntelliJ: fails.
Running tests through sbt on the command line: works.
Running tests through IntelliJ after a successful run through the command line: works.

**Comment by onelson** [comment]
Yeah, this is an IntelliJ problem ;)

I popped open the run configuration for the test suite and noticed some new options I hadn't seen before, such as "use sbt." When I checked the box, I started getting usable results.
